title: Hello, humans! I'm Shreya Pramanik
description: > # this means to ignore newlines until "baseurl:"
  Entrepreneur, blogger in between travels. Nature lover, wants to make a positive impact on the world. Environmentalist.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shreya Pramanik # add your name
author-img: shreya.jpg # add your photo
about-author: Entrepreneur, blogger in between travels. Nature lover, wants to make a positive impact on the world. Environmentalist. # add description
social-twitter: pramanikshreya
social-facebook: pramanikshreya
social-github: pramanikshreya
social-linkedin: pramanikshreya
social-email: pramanikshreya@gmail.com
youtube_channel: UCasp0XRuor1cq7b04zgV9jA
youtube_channel_name: Purkinje

# Disqus
discus-identifier: pramanikshreya # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
